repos:
  -   repo: https://github.com/awebdeveloper/pre-commit-stylelint
      rev: 0.1.1
      hooks:
        -   id: stylelint
        -   additional_dependencies: ['stylelint@15.11.0', 'stylelint-config-standard@34.0.0']
